### ISSUE TITLE
`Failed to disable all other displays` during `setup_sunvdm.ps1`

### ISSUE THREAD

**Issue by drewmullen** [LeGeRyChEeSe/Sunshine-AIO#4]
Thanks for putting all this together. I am getting the following error in `sunvdm.log` when trying to start a stream:

```
Setting up a moonlight monitor with 1280x720@60 with hdr off
Enabling the virtual display.
Microsoft PnP Utility

Failed to enable device:  ROOT\DISPLAY\0001
The device is not connected.

Setting up the virtual display and disabling other displays.
Disabling all other displays.
Failed to disable all other displays.
At C:\Users\dmwin\Setup\sunshine-virtual-monitor-main\setup_sunvdm.ps1:74 char:9
+         Throw "Failed to disable all other displays."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to disable all other displays.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to disable all other displays.
 ```

sunshine main dir:
![image](https://github.com/user-attachments/assets/17a4284e-5ac2-442d-985c-1903b74cacbd)

device manager:
![image](https://github.com/user-attachments/assets/5420fa41-602f-4f44-a0f7-eb8765d0e40a)

**Comment by pete-mcneill** [comment]
Also getting the same issue

**Comment by LeGeRyChEeSe** [comment]
Hi!

I've just push a new version of the script that’s fixed the issue.

Please update the repo with `git pull` then install Virtual Display Driver again to fix the issue.

Also the command for executing the script has changed. Please see the README.md.

**Comment by pete-mcneill** [comment]
Unfortunately no change for me with the changes. I've been debugging and seems to be coming from the Virtual display ps1 script.

This line in particular
`pnputil /enable-device /deviceid root\iddsampledriver`

Running it by itself to try and turn on my virtual display hits the same error in a console. So I'm guessing it's something to do with the name of the device which I'm not familiar with. I will raise on that repo too.

**Comment by LeGeRyChEeSe** [comment]
Go to Device Manager and completely uninstall the `IddSampleDriver` device then execute the AIO tool again and install only Virtual Display Driver.

**Comment by pete-mcneill** [comment]
Tried a fresh install of everything and have ended up with no logging from the sunshine virtual monitor. But found in sunshine I'm getting this log:

`Error: [powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\Sunshine-AIO\tools\sunshine-virtual-monitor-main\sunshine-virtual-monitor-main\setup_sunvdm.ps1" %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > "C:\Sunshine-AIO\tools\sunshine-virtual-monitor-main\sunshine-virtual-monitor-main\sunvdm.log" 2>&1] failed with code [1]`

Still trying to debug to see if I can find more info

**Comment by Atsirkunov** [comment]
Having the same issue, but if I enable/disable the IddSampleDriver - then it suddenly works normally to turn it on and off, but lasts only until the next restart

**Comment by LeGeRyChEeSe** [comment]
The issue was solved with the new release.
1. Go to your root directory of the project `Sunshine-AIO`, open a Windows Terminal and run the following command to get the latest release of the script:
```git
git pull
```
2. Then completely uninstall the IddSampleDriver from `Device Manager` and make sure to tick the `Remove the driver`.
3. Execute the `Sunshine AIO Tool` script with the following command :
```batch
virtualenv-python-sunshine-aio\Scripts\python.exe src\main.py
```
4. Select `3. Download and Install Virtual Display Driver`

The problem should be solved now.

If you still have issues, try to run the install everything part and skip the Sunshine installation part by canceling the installation when it's prompted.

**Comment by pete-mcneill** [comment]
For me this setup repo works correctly but all the issues I have on our connection in the sunshine-virtual-monitor.

I've started fresh today to make sure and pulled this code along with latest running instructions.

My first issue is with `pnputil /enable-device /deviceid root/iddsampledriver` in the setup_sunvdm.ps1 script. It doesn't like the /deviceid parameter and returns the above help usage instructions I've posted above, if I change this to my actual virtual display instance id it works:
`pnputil /enable-device ROOT\DISPLAY\0000`

The script then looks for a display source description matching "IddSampleDriver Device HDR" I've logged out each description and all of mine are NVIDIA GeFore RTX 3070 so it never sets the vdDisplay variable.

And then because of that when it tries to set the primary monitor and disable all the others it fails as the vdDisplay is empty.

**Comment by drewmullen** [comment]
@LeGeRyChEeSe switching to the script in your branch `dev-AIO` fixed this issue for me. However, I had to re-set the Execution-Policy and run Unblock-File again, just FYI.

I also ran into an issue where I had to restart my PC while playnite was on and the ldd driver wasnt disabled properly... basically i had to boot into safe mode to disable it so the PC would start up properly. Is this the only way to solve that kind of issue or is there something else I can do?

**Comment by LeGeRyChEeSe** [comment]
The new release is out and coming with a lot of fixes. Take a look and to get a fresh install you should execute the program again because of some bugs and some issues fixed now.

**Comment by LeGeRyChEeSe** [comment]
You don’t need to uninstall anything. Just execute the program.

**Comment by MarcioFCMartins** [comment]
I am still having the same issue. It seems that the issue is that when my PC is restarted, the Virtual Display device is considered disconnected (notice the status):

```
$ pnputil /enum-devices /class Display
Microsoft PnP Utility

Instance ID:                ROOT\DISPLAY\0000
Device Description:         IddSampleDriver Device HDR
Class Name:                 Display
Class GUID:                 {4d36e968-e325-11ce-bfc1-08002be10318}
Manufacturer Name:          <Your manufacturer name>
Status:                     Disconnected
Driver Name:                oem43.inf
```

At this stage I  get the same error:

```
$ pnputil /enable-device /deviceid root\iddsampledriver
Microsoft PnP Utility

Failed to enable device:  ROOT\DISPLAY\0000
The device is not connected.
```

After manually enabling and disabling the monitor in the Device Manager, the status of the Virtual display changes from `Disconnected` to `Disabled` and now it works:

```
$ pnputil /enum-devices /class Display
Microsoft PnP Utility

Instance ID:                ROOT\DISPLAY\0000
Device Description:         IddSampleDriver Device HDR
Class Name:                 Display
Class GUID:                 {4d36e968-e325-11ce-bfc1-08002be10318}
Manufacturer Name:          <Your manufacturer name>
Status:                     Disabled
Driver Name:                oem43.inf

$ pnputil /enable-device /deviceid root\iddsampledriver

Microsoft PnP Utility

Enabling device:          ROOT\DISPLAY\0000
Device enabled successfully.
```

Now I can successfully start a moonlight stream without error.

No idea how/what controls the "disconnected" status of the device. Any tips?

**Comment by vincjl** [comment]
I managed to enable 'Disconnected' display by running this command

`Get-PnpDevice -FriendlyName 'IddSampleDriver Device HDR' | Enable-PnpDevice -Confirm`

You may want to try and replace line 34 of file setup_sunvdm.ps1:
''''
Write-Host "Enabling the virtual display."
Get-PnpDevice -FriendlyName 'IddSampleDriver Device HDR' | Enable-PnpDevice -Confirm:$false
''''

This may not be needed, but I also replaced line 6 of file teardown_sunvdm.ps1:
''''
Write-Host "Removing the moonlight display."
Get-PnpDevice -FriendlyName 'IddSampleDriver Device HDR' | Disable-PnpDevice -Confirm:$false
''''

**Comment by LeGeRyChEeSe** [comment]
@MarcioFCMartins Thank you for the analyze, i didn’t know this particularity !

@vincjl Thanks you for the fix, this is very helpful !

I'm analyzing and adjusting the code for Sunshine Virtual Monitor. It contains a few imperfections that create a lot of mistakes for many of you. I'll test the commands and integrate them into the script if I don't have any problems.

I'm also working on a Sunshine-AIO auto-update... So it could take some times before the next release because i'm running with many issues 😀
